### ISSUE TITLE
`format` field in swagger 2.0 makes upload fail

### ISSUE THREAD

**Issue by benjamine** [apicollective/apibuilder#711]
I tried to upload a swagger 2.0 schema,
with this model:
```
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "email"
      ],
      "description": "a person that uses any system at our company"
    }
  },
```

and I get this error:

`java.lang.RuntimeException: Failed to resolve definitions: User`

if I remove `format`:
```
          "format": "email"
```

upload works fine.

**Comment by rlmartin** [comment]
I also saw this. I suspect that for certain standard `format` values (`int32`, `uuid`, etc) this works fine. But it should not fail on unrecognized `format`s - especially because (I believe) Swagger supports RegEx in `format`. At the very least, the existing list could be expanded to include more standard formats, such as `email`, `url`, etc.

**Comment by fabiocognigni** [comment]
Another real example I found (making upload fail) is using `html` as a string format.

Shouldn't we always just ignore "unknown" formats (e.g. `email`, `html`) and default  to the ApiBuilder `string` type (and keep the custom mapping for Swagger string formats like `uuid`, `date-time`, etc) ?

PR coming soon.
